# Generated by Django 4.2 on 2025-03-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villarosaapp', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
